language: node_js
node_js: '8'
sudo: required

before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

env:
  - GK_LOCK_COMMIT_AMEND=true

jobs:
  include:
    - stage: test
      name: "Integration Tests"
      script: npm run test:integration

    - name: "Unit Tests"
      addons:
        chrome: stable
        firefox: latest
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script: npm run test:unit

    - stage: deploy
      name: "Firebase (es6-unbundled)"
      if: tag IS present
      script: polymer build --preset es6-unbundled
      deploy: &firebase
        on:
          tags: true
        skip_cleanup: true
        provider: firebase
        project: dorfolympiade
        message: $TRAVIS_TAG
        token:
          secure: fBFXTu+yvxP7wQrbaRy9v+xRnYrPq9yF0FjZm7MRswDOXEihjdVuDjBS24uV7SRwCfHNnG+LBc0RVHXXjBUCEl6KMdL894ENtyVgvN0IHYsc80J2wePyPeC3eSHTUkJ55OlshlNaDXLz3pTdGHmNuMa0fOqz12aIjqdn1/Lw/NWXrc5+pJzuEmWONXX62DgtgaEYVfNPwZ/0hOJe0854Ktw0m235ILp7Al/U9XK37LsXkZVlAE/y12CsNfRXIBtBnMVwidxC+inPkKICJnK8Mz5SiV+P3gaOT1JnFKqepU1ROB/59GnDZsbzcIe0qy3+UWxz0kw6BMUy0tHLUuekDMuFu0c9WP9IiTK6bAEs08fK2NenOJKJ0gzOk+M3Tx8+TrZvbPLWuot17Z6z+87t6M66XDUQMz67G0wo3QSZoCpboLOEiL3+MbXJpf89LRJNgnrTq21wkw0KBQ345fzP9i3UZsCpUe0q1RF4Qaw4TYM8jkAxUY/IKbCWZydbzAfLUPXRrX4Evmf+IfxyDWR8pR5XCEcjXLt01jyiLpPXHGndvPBEeMVSqjTHuzuNbe0F4KKHdazIed4iEBz91TX+K0yQx0Z2HQGPYl7SRcON4CYyDvtpVR4huAzhQQRDHVfKwJ7nm3Tc2hNqW/a3oaLjEBkBSLf9c7+nXQB0iczd/rQ=
