language: node_js
node_js: '8'
sudo: required
cache:
  directories:
    - "node_modules"

before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

env:
  - GK_LOCK_COMMIT_AMEND=true

jobs:
  include:
    - stage: test
      name: "Integration Tests"
      script: npm run test:integration

    - name: "Unit Tests"
      addons:
        chrome: stable
        firefox: latest
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script: npm run test:unit

    - stage: deploy
      name: "Firebase Production (es6-unbundled)"
      if: tag IS present
      script: polymer build --preset es6-unbundled
      deploy: &firebase
        on:
          tags: true
        skip_cleanup: true
        provider: firebase
        project: dorfolympiade
        message: $TRAVIS_TAG
        token: $FIREBASE_TOKEN
    - name: "Firebase Staging (es6-unbundled)"
      if: type != pull_request AND branch = master
      script: polymer build --preset es6-unbundled
      deploy: &firebase
        on:
          branch: master
        skip_cleanup: true
        provider: firebase
        project: dorfolympiade-staging
        message: $TRAVIS_TAG
        token: $FIREBASE_TOKEN
